version: '2'
volumes:
  logcontainer: {}
  datacontainer: {}
services:
  FileBeat:
    image: chube/filebeatfarmadati:latest
    volumes:
    - logcontainer:/var/log/welfinity/
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: "environment_type=aggregation_production"
    tty: true
    stdin_open: true
  FarmadatiTalendJobs:
    image: chube/farmadatiservice:latest
    volumes:
    - logcontainer:/var/log/welfinity/
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: "environment_type=aggregation_production"
    tty: true
    stdin_open: true

