version: '2'
services:
  ElasticSearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    hostname: WelfinityElasticSearch
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      discovery.type: single-node
      xpack.security.enabled: 'false'
    stdin_open: true
    volumes:
    - esdata:/usr/share/elasticsearch/data
    links:
    - LogStash:WelfinityLogstash
    tty: true
    links:
    - LogStash:WelfinityLogstash
    ports:
    - 9200:9200/tcp
    - 9300:9300/tcp
    labels:
      io.rancher.container.pull_image: always
  LogStash:
    image: chube/elk_logstash
    hostname: WelfinityLogstash
    stdin_open: true
    tty: true
    links:
    - ElastiSearch:WelfinityElasticSearch
    ports:
    - 5044:5044/tcp
    labels:
      io.rancher.container.pull_image: always
volumes:
  esdata: