Logstash:
  ports:
  - 5044:5044/tcp
  labels:
    io.rancher.sidekicks: LostashData
    io.rancher.container.pull_image: always
  tty: true
  image: docker.elastic.co/logstash/logstash:5.6.2
  links:
  - ElasticSearch:Datalake
  volumes_from:
  - LostashData
  stdin_open: true
ElasticSearch:
  ports:
  - 9200:9200/tcp
  - 9300:9300/tcp
  environment:
    discovery.type: single-node
    ES_JAVA_OPTS: -Xmx1g -Xms1g
    xpack.security.enabled: false
  labels:
    io.rancher.sidekicks: ESData
    io.rancher.container.pull_image: always
  tty: true
  image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
  stdin_open: true
KibanaData:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  tty: true
  image: busybox
  environment:
    xpack.security.enabled: false
  links:
  - ElasticSearch:elastisearch
  volumes:
  - /usr/share/kibana/config
  stdin_open: true
LostashData:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: busybox
  links:
  - ElasticSearch:Datalake
  volumes:
  - /usr/share/logstash/pipeline/
  - /usr/share/logstash/config/
  stdin_open: true
Kibana:
  ports:
  - 5601:5601/tcp
  environment:
    XPACK_MONITORING_ENABLED: 'false'
  labels:
    io.rancher.sidekicks: KibanaData
    io.rancher.container.pull_image: always
  tty: true
  image: docker.elastic.co/kibana/kibana:5.6.2
  links:
  - ElasticSearch:elastisearch
  volumes_from:
  - KibanaData
  stdin_open: true
ESData:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  tty: true
  image: busybox
  volumes:
  - /usr/share/elasticsearch/data
  stdin_open: true
