version: '2'
volumes:
  esdata: {}
services:
  Kibana:
    image: chube/elk_kibana
    hostname: WelfinityKibana
    environment:
      XPACK_MONITORING_ENABLED: 'false'
    stdin_open: true
    tty: true
    ports:
    - 5601:5601/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: "environment=monitoring_dev"
  ElasticSearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    hostname: ElasticSearch
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      discovery.type: single-node
      xpack.security.enabled: 'false'
    stdin_open: true
    volumes:
    - esdata:/usr/share/elasticsearch/data
    tty: true
    ports:
    - 9200:9200/tcp
    - 9300:9300/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: "environment=monitoring_dev"
  LogStash:
    image: chube/elk_logstash
    hostname: WelfinityLogstash
    stdin_open: true
    tty: true
    ports:
    - 5044:5044/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: "environment=monitoring_dev"